CompanyXwebAuth/Controllers/ChangeLogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CompanyXwebAuth;

namespace CompanyXwebAuth.Controllers
{
    public class ChangeLogsController : Controller
    {
        private CompanyXEntities db = new CompanyXEntities();

        // GET: ChangeLogs
        public ActionResult Index(string sortOrder)
        {
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.EmployeeSortParm = String.IsNullOrEmpty(sortOrder) ? "empl_desc" : "";
            ViewBag.ModifierSortParm = String.IsNullOrEmpty(sortOrder) ? "mod_desc" : "";

            var changeLogs = db.ChangeLogs.Include(c => c.Employee).Include(c => c.Modifier);

            switch (sortOrder)
            {
                case "Date":
                    changeLogs = changeLogs.OrderBy(c => c.ChangeTime);
                    break;
                case "empl_desc":
                    changeLogs = changeLogs.OrderBy(c => c.Employee.FullName);
                    break;
                case "mod_desc":
                    changeLogs = changeLogs.OrderBy(c => c.Employee.FullName);
                    break;
                default:
                    changeLogs = changeLogs.OrderByDescending(c => c.ChangeTime);
                    break;
            }

            return View(changeLogs.ToList());
        }

        // GET: ChangeLogs/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ChangeLog changeLog = db.ChangeLogs.Find(id);
        //    if (changeLog == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(changeLog);
        //}

        // GET: ChangeLogs/Create
        //public ActionResult Create()
        //{
        //    ViewBag.EmployeeId = new SelectList(db.Employees, "IdCode", "FullName");
        //    ViewBag.ModifierId = new SelectList(db.Employees, "IdCode", "FullName");
        //    return View();
        //}

        // POST: ChangeLogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Qnr,EmployeeId,ModifierId,ChangeTime")] ChangeLog changeLog)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.ChangeLogs.Add(changeLog);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.EmployeeId = new SelectList(db.Employees, "IdCode", "FullName", changeLog.EmployeeId);
        //    ViewBag.ModifierId = new SelectList(db.Employees, "IdCode", "FullName", changeLog.ModifierId);
        //    return View(changeLog);
        //}

        // GET: ChangeLogs/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ChangeLog changeLog = db.ChangeLogs.Find(id);
        //    if (changeLog == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.EmployeeId = new SelectList(db.Employees, "IdCode", "FullName", changeLog.EmployeeId);
        //    ViewBag.ModifierId = new SelectList(db.Employees, "IdCode", "FullName", changeLog.ModifierId);
        //    return View(changeLog);
        //}

        // POST: ChangeLogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Qnr,EmployeeId,ModifierId,ChangeTime")] ChangeLog changeLog)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(changeLog).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.EmployeeId = new SelectList(db.Employees, "IdCode", "FullName", changeLog.EmployeeId);
        //    ViewBag.ModifierId = new SelectList(db.Employees, "IdCode", "FullName", changeLog.ModifierId);
        //    return View(changeLog);
        //}

        // GET: ChangeLogs/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    ChangeLog changeLog = db.ChangeLogs.Find(id);
        //    if (changeLog == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(changeLog);
        //}

        // POST: ChangeLogs/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    ChangeLog changeLog = db.ChangeLogs.Find(id);
        //    db.ChangeLogs.Remove(changeLog);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CompanyXwebAuth/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CompanyXwebAuth;
using PagedList;

namespace CompanyXwebAuth.Controllers
{
    public class SkillsController : Controller
    {
        private CompanyXEntities db = new CompanyXEntities();

        // GET: Skills
        public ActionResult Index(string sortOrder, string searchName, string searchSkill, string searchLevel, string button)
        {
           
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.SkillSortParm = String.IsNullOrEmpty(sortOrder) ? "skill_desc" : "";

            ViewData["Courses"] = db.Courses;

            var skills = db.Skills.OrderBy(x => x.Employee.FullName).Include(s => s.SkillCategory).Include(s => s.Employee);

            ViewBag.SkillList = new SelectList(db.Categories, "SkillID", "CategoryName", searchSkill);


            var SkillList = new List<string>();
          
            var SkillQry = from d in db.Categories
                           orderby d.CategoryName
                           select d.CategoryName;

            SkillList.AddRange(SkillQry.Distinct());
          
            ViewBag.searchSkill = new SelectList(SkillList);

            var LevelList = new List<string>();
            
            var LevelQry = from b in db.Skills
                           orderby b.Mastery
                           select b.Mastery;

            LevelList.AddRange(LevelQry.Distinct());
            ViewBag.searchLevel = new SelectList(LevelList);


            if ((button ?? "") == "Reset")
            {
                ModelState.Clear();

                SkillList = new List<string>();
                SkillQry = from d in db.Categories
                           orderby d.CategoryName
                           select d.CategoryName;

                SkillList.AddRange(SkillQry.Distinct());
                ViewBag.searchSkill = new SelectList(SkillList);

                LevelList = new List<string>();
                LevelQry = from b in db.Skills
                           orderby b.Mastery
                           select b.Mastery;

                LevelList.AddRange(LevelQry.Distinct());
                ViewBag.searchLevel = new SelectList(LevelList);
                return View(skills.ToList());
            }


            if (!String.IsNullOrEmpty(searchName))
            {
                skills = skills.Where(s => s.Employee.FullName.Contains(searchName));
            }
            if (!String.IsNullOrEmpty(searchSkill))
            {
                skills = skills.Where(s => s.SkillCategory.CategoryName == searchSkill);
            }
            if (!String.IsNullOrEmpty(searchLevel))
            {
                skills = skills.Where(s => s.Mastery == searchLevel);
            }


            switch (sortOrder)
            {
                case "name_desc":
                    skills = skills.OrderByDescending(s => s.Employee.FullName);
                    break;
                case "skill_desc":
                    skills = skills.OrderBy(s => s.SkillID);
                    break;
                default:
                    skills = skills.OrderBy(s => s.Employee.FullName);
                    break;
            }

            return View(skills.ToList());
        }

        [ChildActionOnly]
        public ActionResult AdminAction()
        {
            if (User.IsInRole("Admin"))
            {                
                return PartialView("_AdminAction");
            }
            return new EmptyResult();
        }

        [ChildActionOnly]
        public ActionResult CreateNew()
        {
            if (User.IsInRole("Admin"))
            {
                return PartialView("_CreateNew");
            }
            return new EmptyResult();
        }

        // GET: Skills/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Skill skill = db.Skills.Find(id);
        //    if (skill == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(skill);
        //}

        // GET: Skills/Create
        public ActionResult Create()
        {
            ViewBag.SkillID = new SelectList(db.Categories, "SkillID", "CategoryName");
            ViewBag.IdCode = new SelectList(db.Employees.OrderBy(x => x.FullName), "IdCode", "FullName");
            var LevelList = new List<string>();
            var LevelQry = from b in db.Skills
                       orderby b.Mastery
                       select b.Mastery;

            LevelList.AddRange(LevelQry.Distinct());
            ViewBag.Mastery = new SelectList(LevelList);

            return View();
        }

        // POST: Skills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Qnr,IdCode,SkillID,Mastery")] Skill skill, string user)
        {
            user = User.Identity.Name;
            if (ModelState.IsValid)
            {
                db.Skills.Add(skill);
                db.SaveChanges();
                Helpers.Helpers.WriteChangeLog(skill.IdCode, "Add skill", user);
                return RedirectToAction("Index");
            }

            ViewBag.SkillID = new SelectList(db.Categories, "SkillID", "CategoryName", skill.SkillID);
            ViewBag.IdCode = new SelectList(db.Employees, "IdCode", "FullName", skill.IdCode);
            return View(skill);
        }

        // GET: Skills/Edit/5
        public ActionResult Edit(int? id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Skill skill = db.Skills.Find(id);
                if (skill == null)
                {
                    return HttpNotFound();
                }
                ViewBag.SkillID = new SelectList(db.Categories, "SkillID", "CategoryName", skill.SkillID);
                ViewBag.IdCode = new SelectList(db.Employees, "IdCode", "FullName", skill.IdCode);
                var LevelList = new List<string>();
                var LevelQry = from b in db.Skills
                               orderby b.Mastery
                               select b.Mastery;

                LevelList.AddRange(LevelQry.Distinct());
                ViewBag.Mastery = new SelectList(LevelList);
                return View(skill);
            }
            else
            {
                return HttpNotFound();
            }
            
        }

        // POST: Skills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Qnr,IdCode,SkillID,Mastery")] Skill skill, string user)
        {
            user = User.Identity.Name;
            if (ModelState.IsValid)
            {
                db.Entry(skill).State = EntityState.Modified;
                db.SaveChanges();
                Helpers.Helpers.WriteChangeLog(skill.IdCode, "Edit skill", user);
                return RedirectToAction("Index");
            }
            ViewBag.SkillID = new SelectList(db.Categories, "SkillID", "CategoryName", skill.SkillID);
            ViewBag.IdCode = new SelectList(db.Employees, "IdCode", "FullName", skill.IdCode);
            return View(skill);
        }

        // GET: Skills/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Skill skill = db.Skills.Find(id);
        //    if (skill == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(skill);
        //}

        // POST: Skills/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Skill skill = db.Skills.Find(id);
        //    db.Skills.Remove(skill);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CompanyXwebAuth/Views/Shared/_EmployeesMenu.cshtml
@Html.ActionLink("Employees", "Index", "Employees")

CompanyXwebAuth/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity.EntityFramework;
@using Microsoft.AspNet.Identity;
@using System.Web.Mvc;
@using CompanyXwebAuth.Models;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Audiowide" rel="stylesheet"> 
    <title>@ViewBag.Title - CompanyX</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("WelcomeScript",false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.Label("CompanyX", null, new { @class = "navbar-brand", @style = "color:red; font-family: 'Audiowide', cursive;" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.Action("EmployeesMenu","Home")</li>
                    <li>@Html.ActionLink("Competence", "Index", "Skills")</li>
                    <li>@Html.ActionLink("Self Development", "Index", "Courses")</li>
                    <li>@Html.ActionLink("History Log", "Index", "ChangeLogs")</li>
                   
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")                
            </div>            
        </div>
       
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CompanyX. All Rights Reserved</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CompanyXwebAuth/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="" />
    <meta name="viewport" content="width=device-width" />
    <link href="https://fonts.googleapis.com/css?family=Audiowide" rel="stylesheet"> 
    <title>@ViewBag.Title - Company X</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundless/modernizr")

    <style>
        html {
            height: 100%;
        }

        body {
            padding: 0;
            display: flex;
            height: 100%;
            align-items: center;
            background-image: url(http://usersthink.com/wp-content/uploads/06-usersthink-stock-image.jpg);
            background-size: cover;
        }

        .jumbotron {
            margin: 0;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
            background-color: rgba(255,255,255,0.8);
            border: solid 3px rgba(255,255,255,0.5);
            font-size: small;
        }

        .form-group {
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>

</head>
<body>
    <div class="container body-content">
        @RenderBody()
        @*<hr />
        <footer>
            <p> &copy; @DateTime.Now.Year - Company X. All Rights Reserved </p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>